### PR TITLE
Fix discovery

### PR DESCRIPTION
**Pull request by nlrb**
Device(s) could be missed in discovery as the process was started before the listener was registered.

### CODE REVIEW

**Comment by WeeJeWel** [comment]
Did you test if this made any difference? The discovery should happen in the next tick anyway.

**Comment by nlrb** [comment]
Yes, for me it makes a difference. It would otherwise miss my first HEOS device.

**Comment by WeeJeWel** [comment]
OK, thanks!

**Comment by nlrb** [comment]
BTW: What I gather from the CLI docs (they're at v1.9 now 😃 ), you should only discover the first device and then stop the discover. The other speakers can be gathered from `get_players`. After that, watch for the `players_changed` event (currently ignored) to update availability (probably relates to #1). If your root speaker goes offline, then re-start the discover.

**Comment by WeeJeWel** [comment]
That was the initial approach we took, but that was very, very buggy (their API isn't the most solid we've encountered anyway).

**Pull request merged**
